# Generated by Django 5.1.1 on 2024-09-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=100)),
                ('vid_path', models.CharField(max_length=255)),
                ('vid_seek_path', models.CharField(max_length=255)),
                ('thumbnail_path', models.CharField(max_length=255)),
                ('vid_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('subtitle_file', models.BinaryField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.video')),
            ],
        ),
    ]
